### ISSUE TITLE
Feature request: support for mapping in reverse order

### ISSUE THREAD

**Issue by AzamatB** [mcabbott/SliceMap.jl#8]
I'm thinking of something like
```Julia
slicemap(f, A; dims, rev::Bool=false)
```
which is when called as
```Julia
slicemap(f, A; dims, rev=true)
```
will start mapping from the end. With this bidirectional LSTM implementation would look like
```Julia
f, b = LSTM(in, out), LSTM(in, out)
Y = [slicemap(f, X; dims=(1,2)); slicemap(b, X; dims=(1,2), rev=true)]
```
The motivation for this is that there are increasingly more neural networks that use both convolutional layers and bidirectional RNN layers within the same architecture. But bidirectional RNN implementations in Flux that I've seen have a vector of matrices as input and output, which is at odds with conv layer that expects one 3D array instead. To work around this, currently, one has to call `vcat`, `permutedims`, etc. many times in the forward pass between those two layers, which increases the number of allocations on GPU.

**Comment by mcabbott** [comment]
Sure, this ought to be easy, see #9. 

But taking the gradient right now gives an error, I'm not sure why.

**Comment by AzamatB** [comment]
Does closing this issue mean that the error with taking the gradient was fixed?

**Comment by mcabbott** [comment]
Is it broken for you? 

This one is working, I think:

https://github.com/mcabbott/SliceMap.jl/pull/9/files#diff-fce720c43af3c52c862fd7451c7374b8R192
